---
title: "text"
runtime: shiny
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


```{r message=FALSE}
library(tidytext)
library(tidyverse)
library(gutenbergr)
library(urltools)
library(shinythemes)
library(shiny)
```


```{r message=FALSE}
peterpan <- gutenberg_download(16) %>%
  mutate(linenumber=row_number()) %>%
  unnest_tokens(word, text) %>%
  anti_join(stop_words)
```


```{r}
ui <- shinyUI(fluidPage(theme=shinytheme("slate"), 
  span(titlePanel('Text Analysis'), style="color:#F9D90A"),
  sidebarLayout(position='right',
    sidebarPanel(
      h4(textOutput('intro'))
  ),
  mainPanel(
    plotOutput("plot1")
    )    
  )
  )
)
  server <- function(input, output) {
    output$intro <- renderText("Quick explanation of text analysis.")
    output$plot1 <- renderPlot({
      peterpan %>%
        count(word) %>%
        filter(n > 50) %>%
        mutate(word = reorder(word, n)) %>%
        ggplot(aes(word, n)) + geom_col() + coord_flip() + ggtitle('Most Common Words in Peter Pan')
    })
  }
  
shinyApp(ui = ui, server = server)
```
